version: "3"

tasks:
  run:
    desc: Run the app
    cmds:
      - GOGLAGS=-mod=mod go run *.go

  build:
    desc: Build the app
    cmds:
      - GOGLAGS=-mod=mod go build -o branch *.go

  clean:
    desc: Clean the app
    cmds:
      - rm -rf dist
